/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit 5 test framework.
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    
    // JSON parsing for LLM API
    implementation("com.google.code.gson:gson:2.10.1")

    // Dotenv for loading environment variables
    implementation("io.github.cdimascio:java-dotenv:5.2.2")
    
    // Google Gen AI SDK
    implementation("com.google.genai:google-genai:1.34.0")
    
    // === RAG Pipeline Dependencies ===
    
    // Apache Lucene for BM25 search
    implementation("org.apache.lucene:lucene-core:9.9.1")
    implementation("org.apache.lucene:lucene-analysis-common:9.9.1")
    implementation("org.apache.lucene:lucene-queryparser:9.9.1")
    
    // DJL (Deep Java Library) for ML inference
    implementation("ai.djl:api:0.29.0")
    implementation("ai.djl.pytorch:pytorch-engine:0.29.0")
    implementation("ai.djl.huggingface:tokenizers:0.29.0")
    
    // Logging
    implementation("org.slf4j:slf4j-simple:2.0.9")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

tasks.named<Test>("test") {
    useJUnitPlatform {
        // Include/exclude tests by tag
        System.getProperty("includeTags")?.let { includeTags(it) }
        System.getProperty("excludeTags")?.let { excludeTags(it) }
    }
    testLogging {
        showStandardStreams = true
        events("passed", "skipped", "failed")
    }
    
    // Forward language filter
    // Usage: ./gradlew :app:test -Dtest.lang=it (or en)
    System.getProperty("test.lang")?.let { systemProperty("test.lang", it) }
    
    // Forward chapter filter
    // Usage: ./gradlew :app:test -Dtest.chapter=4
    System.getProperty("test.chapter")?.let { systemProperty("test.chapter", it) }
    
    // Forward test ID filter (for backward compatibility and single test)
    // Usage: ./gradlew :app:test -Dtest.id=1.1
    System.getProperty("test.id")?.let { systemProperty("test.id", it) }
    
    // Legacy filters (for backward compatibility during transition)
    System.getProperty("test.id.en")?.let { systemProperty("test.id.en", it) }
    System.getProperty("test.id.it")?.let { systemProperty("test.id.it", it) }
}


